// Codecs, MD5, tokenizer and scrambler against the desktop program (OracleCore codecs).
import { scramble, unscramble, md5Hex, md5Base64 } from '../../src/engine/data/Scrambler';
import { Base64Codec } from '../../src/engine/util/Base64Codec';
import { DelimitedTokenizer } from '../../src/engine/util/DelimitedTokenizer';
import { HexEncoder } from '../../src/engine/util/HexEncoder';
import { Utf8Codec } from '../../src/engine/util/Utf8Codec';
import { coreFixture } from '../support/fixtures';

interface Codecs {
  md5: [string, string, string, string, string][];
  base64decode: [string, string][];
  utf8: [string, string, string, string][];
  tokenizer: { input: string; delims: string; keep: boolean; tokens: [string | null, string, string | null][]; escape: string; escapeKeep: string }[];
  scramble: [string, string, string, string][];
}
const f = coreFixture<Codecs>('codecs.json');

test('MD5, base64 and hex of generated bytes', () => {
  for (const [hex, md5h, md5b, b64, upper] of f.md5) {
    const bytes = new HexEncoder(hex).getBytes();
    expect(md5Hex(bytes)).toBe(md5h);
    expect(md5Base64(bytes)).toBe(md5b);
    expect(new Base64Codec(bytes).encodeAll(false)).toBe(b64);
    expect(new HexEncoder(bytes).toString()).toBe(upper);
  }
});

test('lenient base64 decoding', () => {
  for (const [text, hex] of f.base64decode) expect(new HexEncoder(new Base64Codec(text).getBytes()).toHexString(true)).toBe(hex);
});

test('Utf8Codec', () => {
  for (const [text, enc, encPlain, back] of f.utf8) {
    expect(new HexEncoder(new Utf8Codec(text).encode()).toHexString(true)).toBe(enc);
    expect(new HexEncoder(new Utf8Codec(text).encode(false)).toHexString(true)).toBe(encPlain);
    expect(new Utf8Codec(new HexEncoder(enc).getBytes()).toString()).toBe(back);
  }
});

test('DelimitedTokenizer', () => {
  for (const c of f.tokenizer) {
    const t = new DelimitedTokenizer(c.delims);
    t.setInput(c.input);
    const got: [string | null, string, string | null][] = [];
    for (let k = 0; k < 20; k++) {
      const tok = t.nextToken(c.keep);
      got.push([tok, t.getDelimiter(), t.getRemaining()]);
      if (tok == null) break;
    }
    expect(got, JSON.stringify(c.input)).toEqual(c.tokens);
    expect(DelimitedTokenizer.escape(c.input, c.delims)).toBe(c.escape);
    expect(DelimitedTokenizer.escape(c.input, c.delims, true)).toBe(c.escapeKeep);
  }
});

test('Scrambler', () => {
  for (const [s, key, scr, unscr] of f.scramble) {
    expect(scramble(s, key)).toBe(scr);
    expect(unscramble(s, key)).toBe(unscr);
    expect(unscramble(scr, key)).toBe(s);
  }
});
