#!/usr/bin/env bash
# The server side of deploy.sh. Runs as root on the production server, piped over ssh:
#
#   remote.sh prepare <node-version> <node-sha256>   service user, directories, Node
#   remote.sh activate <release-id>                  units, switch release, Apache, tests
#   remote.sh rollback [<release-id>]                switch back (default: the previous release)
#
# With DRY_RUN=1, commands that change anything are printed instead of run; read-only
# checks still run. Never restarts Apache; reloads it only after `apachectl configtest`
# passes, and never edits Apache files other than /etc/httpd/conf.d/logic2010.conf.

# Release names are generated by deploy.sh (digits, letters, '-'), so `ls` is safe for them.
# shellcheck disable=SC2012
set -euo pipefail

APP_ROOT=/opt/logic2010
RELEASES=$APP_ROOT/app/releases
CURRENT=$APP_ROOT/app/current
DATA=/var/lib/logic2010
SERVICE_USER=logic2010
SERVICE=logic2010.service
UNITS=(logic2010.service logic2010-backup.service logic2010-backup.timer)
UNIT_DIR=/etc/systemd/system
APACHE_CONF=/etc/httpd/conf.d/logic2010.conf
LOCAL_URL=http://127.0.0.1:8710/logic2010
PUBLIC_HOST=motiwala.ca
KEEP_RELEASES=${KEEP_RELEASES:-5}
DRY_RUN=${DRY_RUN:-0}
TMP_DIR=""

say() { printf '  [server] %s\n' "$*"; }
warn() { printf '  [server] WARNING: %s\n' "$*" >&2; }
die() { printf '  [server] ERROR: %s\n' "$*" >&2; exit 1; }

# Runs a command that changes the system (only prints it in a dry run).
run() {
  if [[ $DRY_RUN == 1 ]]; then
    printf '  [server] would run:'
    printf ' %q' "$@"
    printf '\n'
  else
    "$@"
  fi
}

require_root_and_tools() {
  [[ $EUID -eq 0 ]] || die "must run as root"
  local cmd
  for cmd in systemctl apachectl curl tar sha256sum restorecon useradd install cmp; do
    command -v "$cmd" >/dev/null || die "missing command: $cmd"
  done
}

# --- prepare ---------------------------------------------------------------------------

ensure_user() {
  if id -u "$SERVICE_USER" >/dev/null 2>&1; then
    say "user $SERVICE_USER exists"
  else
    say "creating system user $SERVICE_USER"
    run useradd --system --user-group --home-dir "$DATA" --no-create-home \
      --shell /sbin/nologin --comment "Logic 2010 web server" "$SERVICE_USER"
  fi
}

ensure_dirs() {
  run install -d -m 755 -o root -g root "$APP_ROOT" "$APP_ROOT/app" "$RELEASES"
  run install -d -m 700 -o "$SERVICE_USER" -g "$SERVICE_USER" "$DATA" "$DATA/backups"
  say "directories: $APP_ROOT (root, 755), $DATA (logic2010, 700)"
}

ensure_node() {
  local version=$1 sha256=$2
  local name="node-v$version-linux-x64"
  local tarball="$name.tar.gz"
  local installed
  installed=$("$APP_ROOT/node/bin/node" --version 2>/dev/null || true)
  if [[ $installed == "v$version" ]]; then
    say "Node $installed already installed"
    return
  fi
  say "installing Node v$version (found: ${installed:-none})"
  if [[ ! -x $APP_ROOT/$name/bin/node ]]; then
    if [[ $DRY_RUN == 1 ]]; then
      say "would download https://nodejs.org/dist/v$version/$tarball, check SHA-256 $sha256"
      say "  against SHASUMS256.txt, and unpack it to $APP_ROOT/$name"
    else
      TMP_DIR=$(mktemp -d)
      trap 'rm -rf "$TMP_DIR"' EXIT
      curl -fsSL --retry 3 -o "$TMP_DIR/$tarball" "https://nodejs.org/dist/v$version/$tarball"
      curl -fsSL --retry 3 -o "$TMP_DIR/SHASUMS256.txt" "https://nodejs.org/dist/v$version/SHASUMS256.txt"
      local published
      published=$(awk -v f="$tarball" '$2 == f { print $1 }' "$TMP_DIR/SHASUMS256.txt")
      [[ $published == "$sha256" ]] || die "SHASUMS256.txt lists '$published' for $tarball, expected $sha256"
      (cd "$TMP_DIR" && printf '%s  %s\n' "$sha256" "$tarball" | sha256sum -c --quiet -) || die "SHA-256 mismatch for $tarball"
      # Unpack next to the final location, then rename (so a failed unpack leaves nothing half-done).
      rm -rf "$APP_ROOT/$name.partial"
      mkdir "$APP_ROOT/$name.partial"
      tar -xzf "$TMP_DIR/$tarball" -C "$APP_ROOT/$name.partial" --strip-components=1 --no-same-owner
      chmod -R go-w "$APP_ROOT/$name.partial"
      mv -T "$APP_ROOT/$name.partial" "$APP_ROOT/$name"
    fi
  fi
  if [[ -e $APP_ROOT/node && ! -L $APP_ROOT/node ]]; then
    die "$APP_ROOT/node exists and is not a symlink; move it away first"
  fi
  run ln -sfn "$name" "$APP_ROOT/node.new"
  run mv -Tf "$APP_ROOT/node.new" "$APP_ROOT/node"
  run restorecon -R "$APP_ROOT/$name"
  if [[ $DRY_RUN != 1 ]]; then
    [[ $("$APP_ROOT/node/bin/node" --version) == "v$version" ]] || die "Node did not install correctly"
    say "Node $("$APP_ROOT/node/bin/node" --version) installed at $APP_ROOT/node"
  fi
}

prepare() {
  local version=${1:?node version} sha256=${2:?node sha256}
  require_root_and_tools
  ensure_user
  ensure_dirs
  ensure_node "$version" "$sha256"
}

# --- activate --------------------------------------------------------------------------

# Waits for the server to answer on 127.0.0.1 and checks the API and the app shell.
smoke_test() {
  [[ $DRY_RUN == 1 ]] && { say "would smoke-test $LOCAL_URL/api/health and $LOCAL_URL/"; return 0; }
  local i
  for i in $(seq 1 30); do
    if curl -fsS -o /dev/null "$LOCAL_URL/api/health" 2>/dev/null; then break; fi
    sleep 0.5
  done
  local health
  health=$(curl -fsS "$LOCAL_URL/api/health") || return 1
  [[ $health == *'"ok":true'* ]] || return 1
  curl -fsS "$LOCAL_URL/" | grep -qi '<!doctype html' || return 1
  say "smoke test passed: $health"
}

# Points `current` at a release (atomically, by renaming a new symlink over it).
switch_to() {
  local release=$1
  run ln -sfn "releases/$release" "$APP_ROOT/app/current.new"
  run mv -Tf "$APP_ROOT/app/current.new" "$CURRENT"
  say "current -> releases/$release"
}

install_units() {
  local release_dir=$1 changed=0 unit
  for unit in "${UNITS[@]}"; do
    if cmp -s "$release_dir/deploy/$unit" "$UNIT_DIR/$unit"; then
      say "$unit unchanged"
    else
      say "installing $UNIT_DIR/$unit"
      run install -m 644 -o root -g root "$release_dir/deploy/$unit" "$UNIT_DIR/$unit"
      run restorecon "$UNIT_DIR/$unit"
      changed=1
    fi
  done
  if [[ $changed == 1 ]]; then run systemctl daemon-reload; fi
}

# Installs the Apache snippet; reloads Apache only if the whole configuration tests OK,
# otherwise puts the previous snippet back (or removes the new one) and stops.
install_apache_conf() {
  local release_dir=$1
  local new="$release_dir/deploy/logic2010-apache.conf"
  if cmp -s "$new" "$APACHE_CONF"; then
    say "Apache config unchanged; not reloading Apache"
    return
  fi
  say "installing $APACHE_CONF"
  if [[ $DRY_RUN == 1 ]]; then
    run install -m 644 -o root -g root "$new" "$APACHE_CONF"
    run restorecon "$APACHE_CONF"
    run apachectl configtest
    say "would reload Apache (systemctl reload httpd) only if configtest passes"
    return
  fi
  local saved=""
  if [[ -f $APACHE_CONF ]]; then
    saved=$(mktemp)
    cp -p "$APACHE_CONF" "$saved"
  fi
  install -m 644 -o root -g root "$new" "$APACHE_CONF"
  restorecon "$APACHE_CONF"
  if apachectl configtest; then
    systemctl reload httpd
    say "Apache reloaded"
    if [[ -n $saved ]]; then rm -f "$saved"; fi
  else
    if [[ -n $saved ]]; then
      cp -p "$saved" "$APACHE_CONF"
      rm -f "$saved"
    else
      rm -f "$APACHE_CONF"
    fi
    die "apachectl configtest failed: Apache NOT reloaded; $APACHE_CONF restored to its previous state"
  fi
}

# Checks the public URL through Apache (resolving the site name to this machine).
public_test() {
  [[ $DRY_RUN == 1 ]] && { say "would check https://$PUBLIC_HOST/logic2010/ through Apache"; return 0; }
  local resolve=(--resolve "$PUBLIC_HOST:443:127.0.0.1")
  if curl -fsS "${resolve[@]}" "https://$PUBLIC_HOST/logic2010/api/health" >/dev/null &&
    [[ $(curl -sS -o /dev/null -w '%{http_code} %{redirect_url}' "${resolve[@]}" "https://$PUBLIC_HOST/logic2010") == "301 https://$PUBLIC_HOST/logic2010/" ]]; then
    say "https://$PUBLIC_HOST/logic2010/ works through Apache"
  else
    warn "https://$PUBLIC_HOST/logic2010/ did not answer as expected through Apache; check /var/log/httpd/ssl_error_log"
  fi
}

# Keeps the newest `keep` releases, plus the active one and `also_keep` (the previous one).
prune_releases() {
  local keep=$1 also_keep=${2:-} active
  active=$(basename "$(readlink "$CURRENT" 2>/dev/null || echo none)")
  local releases=()
  mapfile -t releases < <(ls -1 "$RELEASES" 2>/dev/null | sort)
  local count=${#releases[@]} i
  for ((i = 0; i < count - keep; i++)); do
    [[ ${releases[i]} == "$active" || ${releases[i]} == "$also_keep" ]] && continue
    say "removing old release ${releases[i]}"
    run rm -rf -- "${RELEASES:?}/${releases[i]}"
  done
}

activate() {
  local release=${1:?release id}
  local release_dir=$RELEASES/$release
  require_root_and_tools
  if [[ $DRY_RUN == 1 && ! -d $release_dir ]]; then
    say "(dry run: release $release was not uploaded, so its files cannot be compared here)"
    say "would install units ${UNITS[*]} into $UNIT_DIR if changed, then systemctl daemon-reload"
    say "would install $APACHE_CONF if changed, run apachectl configtest, and reload httpd only if it passes"
  else
    [[ -f $release_dir/dist/index.html ]] || die "$release_dir/dist/index.html missing"
    [[ -f $release_dir/server/server.mjs ]] || die "$release_dir/server/server.mjs missing"
    run restorecon -R "$release_dir"
  fi

  local previous=""
  previous=$(basename "$(readlink "$CURRENT" 2>/dev/null)" 2>/dev/null || true)
  if [[ -n $previous && -f $DATA/logic2010.db ]] && systemctl cat logic2010-backup.service >/dev/null 2>&1; then
    say "backing up the database before switching"
    run systemctl start logic2010-backup.service
  fi

  if [[ -d $release_dir ]]; then install_units "$release_dir"; fi
  switch_to "$release"
  run systemctl enable --quiet "$SERVICE" logic2010-backup.timer
  run systemctl restart "$SERVICE"
  run systemctl start logic2010-backup.timer

  if ! smoke_test; then
    warn "smoke test failed; recent log:"
    journalctl -u "$SERVICE" -n 30 --no-pager >&2 || true
    if [[ -n $previous && $previous != "$release" ]]; then
      warn "switching back to $previous"
      switch_to "$previous"
      systemctl restart "$SERVICE"
    fi
    die "deployment of $release failed"
  fi

  if [[ -d $release_dir ]]; then install_apache_conf "$release_dir"; fi
  public_test
  prune_releases "$KEEP_RELEASES" "$previous"
  say "deployed release $release (previous: ${previous:-none})"
}

rollback() {
  require_root_and_tools
  local target=${1:-}
  local active
  active=$(basename "$(readlink "$CURRENT" 2>/dev/null)" 2>/dev/null || true)
  if [[ -z $target ]]; then
    # The newest release older than the active one.
    target=$(ls -1 "$RELEASES" | sort | awk -v a="$active" '$0 < a' | tail -n 1)
    [[ -n $target ]] || die "no release older than ${active:-none} to roll back to"
  fi
  [[ -f $RELEASES/$target/server/server.mjs ]] || die "no such release: $target"
  say "rolling back from ${active:-none} to $target"
  switch_to "$target"
  run systemctl restart "$SERVICE"
  smoke_test || die "rolled-back release $target failed its smoke test"
  say "available releases: $(ls -1 "$RELEASES" | tr '\n' ' ')"
}

case ${1:-} in
  prepare) shift; prepare "$@" ;;
  activate) shift; activate "$@" ;;
  rollback) shift; rollback "$@" ;;
  *) die "usage: remote.sh prepare <node-version> <sha256> | activate <release> | rollback [<release>]" ;;
esac
